### PR TITLE
Vue 3 - Next (beta)

### LINKED ISSUE #143: How to use with nuxt ?
I added a plugin 

`/plugins/menu.js`
```
'use strict'
import Vue from 'Vue'
import VueStripeMenu from 'vue-stripe-menu'
import 'vue-stripe-menu/dist/vue-stripe-menu.css'

Vue.use(VueStripeMenu)
```

And i got a lot of error,

```bash
 WARN  in ./node_modules/Vue/dist/vue.runtime.esm.js                                                                                                           friendly-errors 16:39:26  

There are multiple modules with names that only differ in casing.                                                                                              friendly-errors 16:39:26  
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* D:\WorkFolder\Devlopment\personnal\Taff\DPliance\DPlianceWebsite\node_modules\Vue\dist\vue.runtime.esm.js
    Used by 2 module(s), i. e.
    D:\WorkFolder\Devlopment\personnal\Taff\DPliance\DPlianceWebsite\node_modules\babel-loader\lib\index.js??ref--2-0!D:\WorkFolder\Devlopment\personnal\Taff\DPliance\DPlianceWebsite\pl
ugins\menu.js
* D:\WorkFolder\Devlopment\personnal\Taff\DPliance\DPlianceWebsite\node_modules\vue\dist\vue.runtime.esm.js
    Used by 80 module(s), i. e.
    D:\WorkFolder\Devlopment\personnal\Taff\DPliance\DPlianceWebsite\node_modules\babel-loader\lib\index.js??ref--2-0!D:\WorkFolder\Devlopment\personnal\Taff\DPliance\DPlianceWebsite\.n
uxt\client.js
                                                                                                                                                               friendly-errors 16:39:26  

 ERROR  Failed to compile with 70 errors                                                                                                                       friendly-errors 16:39:26  

These dependencies were not found:                                                                                                                             friendly-errors 16:39:26  
                                                                                                                                                               friendly-errors 16:39:26  
* core-js/modules/es6.array.find in ./.nuxt/client.js                                                                                                          friendly-errors 16:39:26  
* core-js/modules/es6.array.from in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js and 1 other                                                      friendly-errors 16:39:26  
* core-js/modules/es6.array.iterator in ./.nuxt/client.js, ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/TheHeader.vue?vue&typ
e=script&lang=js& and 2 others
* core-js/modules/es6.date.to-string in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js and 1 other                                                  friendly-errors 16:39:26  
* core-js/modules/es6.function.name in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js and 1 other                                                   friendly-errors 16:39:26  
* core-js/modules/es6.number.constructor in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/TeaserColumn.vue?vue&type=script&lan
g=js&, ./node_modules/vue-stripe-menu/dist/vue-stripe-menu.common.js
* core-js/modules/es6.object.assign in ./.nuxt/client.js, ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/TheHeader.vue?vue&type
=script&lang=js& and 2 others
* core-js/modules/es6.object.keys in ./.nuxt/client.js, ./node_modules/vue-stripe-menu/dist/vue-stripe-menu.common.js                                          friendly-errors 16:39:26  
* core-js/modules/es6.object.set-prototype-of in ./node_modules/vue-stripe-menu/dist/vue-stripe-menu.common.js                                                 friendly-errors 16:39:26  
* core-js/modules/es6.object.to-string in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js and 2 others                                               friendly-errors 16:39:26  
* core-js/modules/es6.promise in ./.nuxt/client.js, ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/TheHeader.vue?vue&type=scrip
t&lang=js& and 2 others
* core-js/modules/es6.regexp.constructor in ./.nuxt/utils.js, ./node_modules/vue-stripe-menu/dist/vue-stripe-menu.common.js                                    friendly-errors 16:39:27  
* core-js/modules/es6.regexp.match in ./.nuxt/client.js, ./node_modules/vue-stripe-menu/dist/vue-stripe-menu.common.js                                         friendly-errors 16:39:27  
* core-js/modules/es6.regexp.replace in ./.nuxt/utils.js, ./.nuxt/components/nuxt.js and 1 other                                                               friendly-errors 16:39:27  
* core-js/modules/es6.regexp.search in ./.nuxt/utils.js                                                                                                        friendly-errors 16:39:27  
* core-js/modules/es6.regexp.split in ./.nuxt/utils.js, ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./.nuxt/components/nuxt-build-indicat
or.vue?vue&type=script&lang=js& and 1 other
* core-js/modules/es6.regexp.to-string in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js and 1 other                                                friendly-errors 16:39:27  
* core-js/modules/es6.string.includes in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js and 1 other                                                 friendly-errors 16:39:27  
* core-js/modules/es6.string.iterator in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js and 1 other                                                 friendly-errors 16:39:27  
* core-js/modules/es6.string.repeat in ./.nuxt/utils.js                                                                                                        friendly-errors 16:39:27  
* core-js/modules/es6.string.starts-with in ./.nuxt/utils.js                                                                                                   friendly-errors 16:39:27  
* core-js/modules/es6.symbol in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js and 1 other                                                          friendly-errors 16:39:27  
* core-js/modules/es7.array.includes in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js and 1 other                                                  friendly-errors 16:39:27  
* core-js/modules/es7.object.get-own-property-descriptors in ./.nuxt/index.js                                                                                  friendly-errors 16:39:27  
* core-js/modules/es7.promise.finally in ./.nuxt/client.js, ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/TheHeader.vue?vue&ty
pe=script&lang=js& and 2 others
* core-js/modules/es7.symbol.async-iterator in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js and 1 other                                           friendly-errors 16:39:27  
* core-js/modules/web.dom.iterable in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js and 1 other                                                    friendly-errors 16:39:27  
                                                                                                                                                               friendly-errors 16:39:27  
To install them, you can run: npm install --save core-js/modules/es6.array.find core-js/modules/es6.array.from core-js/modules/es6.array.iterator core-js/modules/es6.date.to-string core
-js/modules/es6.function.name core-js/modules/es6.number.constructor core-js/modules/es6.object.assign core-js/modules/es6.object.keys core-js/modules/es6.object.set-prototype-of core-j
s/modules/es6.object.to-string core-js/modules/es6.promise core-js/modules/es6.regexp.constructor core-js/modules/es6.regexp.match core-js/modules/es6.regexp.replace core-js/modules/es6
.regexp.search core-js/modules/es6.regexp.split core-js/modules/es6.regexp.to-string core-js/modules/es6.string.includes core-js/modules/es6.string.iterator core-js/modules/es6.string.r
epeat core-js/modules/es6.string.starts-with core-js/modules/es6.symbol core-js/modules/es7.array.includes core-js/modules/es7.object.get-own-property-descriptors core-js/modules/es7.pr
omise.finally core-js/modules/es7.symbol.async-iterator core-js/modules/web.dom.iterable
```

How to use with nuxt ?

### LINKED ISSUE #196: Not Vue 3 compatible
Can't seem to get it to work with Vue 3.

### LINKED ISSUE #246: border-radius is stretched with the background

### PR DESCRIPTION
**Pull request by oleksiikhr**
close #143
close #196
close #246

Bringing the repository to new standards and technologies.

### CODE REVIEW

File: docs/src/components/BaseHeader.vue [hunk 1]
```diff
@@ -0,0 +1,66 @@
+<template>
+  <vsm-menu ref="header" :menu="menu" v-bind="$attrs">
+    <template #before-nav>
+      <li class="vsm-mob-full">
+        <stripe-logo />
+      </li>
+    </template>
+    <template #default="{ item }">
+      <component :is="item.component" />
+    </template>
```
Comment (alexanderhorner) [inline docs/src/components/BaseHeader.vue:10]: Maybe do something like this:
```vue
<template #default>
    <div>Page 1</div>
    <div>Page 2</div>
    <div>Page 3</div>
</template>
```
or
```vue
<template #default>
    <template>Page 1</template>
    <template>Page 2</template>
    <template>Page 3</template>
</template>
```

```vue
<template #default>
    <template v-for="item in menuItems">{{ item.content }}</template>
</template>
```
This gives the user more control, although I don't know how you would integrate the nav bar and all that custom attribute logic that way.

Comment (alexanderhorner) [reply docs/src/components/BaseHeader.vue:10]: Maybe with a prop or something that holds a menu item object with all the extra info like title, element, etc.

**Comment by alexanderhorner** [comment]
Hey, how are you doing? Any way to help with this?

**Comment by alexanderhorner** [comment]
This is awesome!! and works flawlessly. Just can't deploy it yet because of the package.json exports issue.

**Comment by alexanderhorner** [comment]
Another thing I noticed is that animating the background using the width and height properties stutters in power saving mode (and I assume also in some other cases, on slow devices for example). 

It’s the straight forward way, and maybe it can be fixed some other way? If not, you maybe could use transform scale, but then do some math to correct the border-radius… idk, I can’t think of some other solution to that rn. Some more testing can’t hurt.
